version: 2

project_name: opencapy

before:
  hooks:
    - go mod tidy

builds:
  - id: opencapy
    binary: opencapy
    main: ./cmd/opencapy
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "opencapy_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: richardyc
    name: opencapy
  draft: false
  prerelease: auto
  make_latest: true
