# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opencapy < Formula
  desc "Your machines, mirrored. Code from anywhere."
  homepage "https://opencapy.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/richardyc/opencapy/releases/download/v0.1.0/opencapy_darwin_amd64.tar.gz"
      sha256 "986b63df3e2e971a4b42ff64bff75892721a49343aafa5832cec996736bff016"

      define_method(:install) do
        bin.install "opencapy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/richardyc/opencapy/releases/download/v0.1.0/opencapy_darwin_arm64.tar.gz"
      sha256 "4f1b3b4cc429f6efb82ec8d6a08b70866aa45b7fed8fd025261ba158c80e0b55"

      define_method(:install) do
        bin.install "opencapy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardyc/opencapy/releases/download/v0.1.0/opencapy_linux_amd64.tar.gz"
      sha256 "bca2107b471e7ebe2977c0e8291ecfcc9e44e00c45f97fb7e40bfeaf5dfb8fab"
      define_method(:install) do
        bin.install "opencapy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardyc/opencapy/releases/download/v0.1.0/opencapy_linux_arm64.tar.gz"
      sha256 "ed8442caa30e17b3150ba9211f2d37f5c93cd584c6d831507e870f54cafa77b4"
      define_method(:install) do
        bin.install "opencapy"
      end
    end
  end

  test do
    system "#{bin}/opencapy", "--help"
  end
end
