# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opencapy < Formula
  desc "Your machines, mirrored. Code from anywhere."
  homepage "https://opencapy.dev"
  version "0.2.22"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/richardyc/opencapy/releases/download/v0.2.22/opencapy_darwin_amd64.tar.gz"
      sha256 "601a399fbbbd345da911563f7dd4bd569b3a10fa64ccb420604b3d1e560cd2aa"

      define_method(:install) do
        bin.install "opencapy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/richardyc/opencapy/releases/download/v0.2.22/opencapy_darwin_arm64.tar.gz"
      sha256 "7178eee066100b605cc7f1dda2d6ec1acafc58da548c87f869e133afa36af112"

      define_method(:install) do
        bin.install "opencapy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardyc/opencapy/releases/download/v0.2.22/opencapy_linux_amd64.tar.gz"
      sha256 "1d3bc5a3505711d85e5a4c53a16d6da81930085d7ec747e30e064848b0776cc2"
      define_method(:install) do
        bin.install "opencapy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardyc/opencapy/releases/download/v0.2.22/opencapy_linux_arm64.tar.gz"
      sha256 "b22cf28ad68d5fedd60bf969c7c789bff8571219b899fc61d83bdbf15f7e3d56"
      define_method(:install) do
        bin.install "opencapy"
      end
    end
  end

  test do
    system "#{bin}/opencapy", "--help"
  end
end
